# Generated by Django 2.0 on 2019-06-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readdetail',
            name='readnum',
        ),
        migrations.AddField(
            model_name='readdetail',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
    ]
